package bitiwise.hack;

// https://leetcode.com/problems/find-the-difference/
/*
* You are given two strings s and t.

String t is generated by random shuffling string s and then
* add one more letter at a random position.Return the letter that was added to t.
* Input: s = "abcd", t = "abcde"
Output: "e"
* */
public class FindDifference {
    public static char findTheDifference(String s, String t) {
        char r=0;
        for(int i=0;i<s.length();i++){
            r^=s.charAt(i);
        }
        for(int i=0;i<t.length();i++){
            r^=t.charAt(i);
        }
        return r;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }
}
