name: Create Jira Ticket on PR

on:
  pull_request:
    types: [opened]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Create Jira Ticket
      id: create_jira
      env:
        JIRA_BASE_URL: "https://justbestvikrant.atlassian.net/"
        JIRA_EMAIL: "justbestvikrant@gmail.com"
        JIRA_API_TOKEN: "ATATT3xFfGF0H6Ft4HrZA3UbaQ-5Z_tqDjXsP34iCGuNzHyjh45C6wIVBh5QxoHMroCIWR92QPJ35QG3A6iQcIZAg654WhcsfH-rr-s69Uza6qWWBAyrpanyWQhg5ohUAQsF3xFm8MEE4EkbFOAEJu5kOfToyYA6YKKitsjYy8WS-3plqn8Mhlw=05E59993"
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
          -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
          --data '{
            "fields": {
              "project": {
                "key": "SCRUM"
              },
              "summary": "PR: '"$PR_TITLE"'",
              "description": "A pull request was created: '"$PR_URL"'.",
              "issuetype": {
                "name": "Task"
                }
            }
          }' \
          "$JIRA_BASE_URL/rest/api/2/issue")
        
        echo $RESPONSE | jq -r '.key' > jira_key.txt
        echo "JIRA_KEY=$(cat jira_key.txt)" >> $GITHUB_ENV

    - name: Notify Telegram
      if: success() && env.JIRA_KEY
      env:
        TG_BOT_TOKEN: "7770839833:AAHqqjKaaYUjZFi8M-5j9NSZwKgazHDTc6g"
        TG_CHAT_ID: "1868146435"
        JIRA_KEY: ${{ env.JIRA_KEY }}
        JIRA_URL: "https://justbestvikrant.atlassian.net/browse/${{ env.JIRA_KEY }}"
      run: |
        curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TG_CHAT_ID" \
          -d "text=Jira Ticket Created: $JIRA_KEY. Visit: $JIRA_URL"
