name: Create Jira Ticket on PR

on:
  pull_request:
    types: [opened]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Create Jira Ticket
      env:
        JIRA_BASE_URL: "https://home.atlassian.com/"
        JIRA_EMAIL: "justbestvikrant@gmail.com"
        JIRA_API_TOKEN: "ATATT3xFfGF0H6Ft4HrZA3UbaQ-5Z_tqDjXsP34iCGuNzHyjh45C6wIVBh5QxoHMroCIWR92QPJ35QG3A6iQcIZAg654WhcsfH-rr-s69Uza6qWWBAyrpanyWQhg5ohUAQsF3xFm8MEE4EkbFOAEJu5kOfToyYA6YKKitsjYy8WS-3plqn8Mhlw=05E59993"
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
          --data '{
            "fields": {
              "project": {
                "key": "YOUR_PROJECT_KEY"
              },
              "summary": "PR: '"$PR_TITLE"'",
              "description": "A pull request was created: '"$PR_URL"'.",
              "issuetype": {
                "name": "Task"
                }
            }
          }' \
          "$JIRA_BASE_URL/rest/api/2/issue"
